### ISSUE TITLE
Version 1.14.1 crashes each time I try to update feeds

### ISSUE THREAD

**Issue by antistress** [flathub/net.sourceforge.liferea#15]
Hi, with latest version, since yesterday I think, liferea crashes each time I try to update feeds

I tried to run `flatpak run  net.sourceforge.liferea` to give more details, but terminal is silent at crash

Thanks

**Comment by mikelolasagasti** [comment]
Can you try with ` flatpak-coredumpctl net.sourceforge.liferea` and once it crashes type `where` or `bt` as described in https://www.figuiere.net/technotes/notes/tn001/ ?

It may be related to https://github.com/lwindolf/liferea/issues/1212

**Comment by Froggy232** [comment]
Hi,
I can confirm that I have the exact same issue, I use flatpak with fedora silverblue.
Downgrading the package solve the problem.
Thanks you

**Comment by antistress** [comment]
Hi,

`$ flatpak info net.sourceforge.liferea` told me : 
Sdk: org.gnome.Sdk/x86_64/42

But then `$ flatpak install --user org.gnome.Sdk/x86_64/42` told me:
Looking for matches…
error: No remote refs found for ‘org.gnome.Sdk/x86_64/42’

**Comment by bbhtt** [comment]
Is the `flathub` remote set systemwide (`flatpak remote-list`)? Then drop the `--user` part.

**Comment by antistress** [comment]
> Is the `flathub` remote set systemwide (`flatpak remote-list`)? Then drop the `--user` part.

Indeed thanks

**Comment by antistress** [comment]
I'm trying to free space to be able to run the command but I'm sure to succeed

**Comment by bbhtt** [comment]
Hello, please test this build to see if it fixes your issue https://github.com/flathub/net.sourceforge.liferea/pull/16#issuecomment-1475263815. You'll probably want to uninstall the one published on Flathub first, test this and then reinstall from Flathub.

**Comment by antistress** [comment]
> Hello, please test this build to see if it fixes your issue [#16 (comment)](https://github.com/flathub/net.sourceforge.liferea/pull/16#issuecomment-1475263815). You'll probably want to uninstall the one published on Flathub first, test this and then reinstall from Flathub (to keep receiving updates).

This build solves the bug for me :)

**Comment by antistress** [comment]
Is there already a new build on flathub ?
Thanks

**Comment by bbhtt** [comment]
> Is there already a new build on flathub ?
> Thanks

Yes, 1.14.2 is published https://beta.flathub.org/apps/net.sourceforge.liferea

But apparently it is again affected by a different crash https://github.com/lwindolf/liferea/issues/1214, so I suggest downgrading the flatpak to 1.14.0 for the time being https://docs.flatpak.org/en/latest/tips-and-tricks.html#downgrading

**Comment by antistress** [comment]
Thanks

**Comment by antistress** [comment]
Ok, I'm back with flathub 1.14.4 version, problem solved for me thanks
