### ISSUE TITLE
Verify the app

### ISSUE THREAD

**Issue by bbhtt** [flathub/net.sourceforge.liferea#53]
Hi @lwindolf would you be willing to verify the application on Flathub?

See https://docs.flathub.org/docs/for-app-authors/verification#im-publishing-an-app-on-flathub-how-do-i-get-it-verified

You already have developer access to this repo, so you can just log in to https://flathub.org/login using your GitHub account, click developer portal from the top left menu:

![image](https://github.com/flathub/net.sourceforge.liferea/assets/62639087/eba5cfc5-3c2d-4d99-8d06-1cfb25fa97d1)

and select liferea:

![image](https://github.com/flathub/net.sourceforge.liferea/assets/62639087/e908d67b-f4c3-46bd-a083-c582266d1545)

Then there should be an option to start the verification process.

![image](https://github.com/flathub/net.sourceforge.liferea/assets/62639087/70fe54c1-e3fe-4042-b5d7-1044e9690274)

Thanks!

**Comment by lwindolf** [comment]
Sorry Liferea having the id of `net.sf.liferea` prevents me from verifying it. There is no more project at Sourceforge :-(

**Comment by bbhtt** [comment]
That's a bummer :( 

Changing the id again involves too much upstream and downstream changes.

I'll close it. Thanks for looking into it.
